libvirt module support
uyuni-project/virtual-host-gatherer pull request #23
Opened 2022-03-11 19:50 UTC by mbelur

2022-03-14 08:37 UTC, moio commented
@cbosdo can you have a look and review this PR please?

2022-03-14 10:29 UTC, cbosdo approved these changes
I am not really an expert in Virtual Host Gatherers, but from the libvirt side it seems good to me. Any reason to use a Virtual Host Gatherer given the `Virtualization` system property gives the same feature with many cool additions?

2022-03-14 18:34 UTC, mbelur commented
> I am not really an expert in Virtual Host Gatherers, but from the libvirt side it seems good to me. Any reason to use a Virtual Host Gatherer given the `Virtualization` system property gives the same feature with many cool additions?

This work is to support using the virtual host gatherer to collect libvirt data independently of SUMA being deployed

2022-03-14 18:34 UTC, mbelur commented on virtual-host-gatherer/lib/gatherer/modules/Libvirt.py
> +                "Missing scheme in uri.Few examples of a valid scheme: qemu, qemu+ssh, qemu+tcp")
Updated

2022-03-15 08:09 UTC, mcalmer requested changes
Please adapt also the spec file to create a sub package for libvirt:
https://github.com/uyuni-project/virtual-host-gatherer/blob/master/virtual-host-gatherer/virtual-host-gatherer.spec

There are a lot of examples for all the other modules.

2022-03-15 16:55 UTC, mbelur commented
> Please adapt also the spec file to create a sub package for libvirt: https://github.com/uyuni-project/virtual-host-gatherer/blob/master/virtual-host-gatherer/virtual-host-gatherer.spec
> 
> There are a lot of examples for all the other modules.

We are planning to update the spec as part of another PR. Let me know if that's okay.

2022-03-15 16:58 UTC, mcalmer commented
We cannot merge until this is done. We do not want to have code in the git which ends up in the source package but is not in any binary package. It is ok if you want to do it in an extra PR, but we will merge only both together.

2022-03-17 17:00 UTC, mbelur commented
> We cannot merge until this is done. We do not want to have code in the git which ends up in the source package but is not in any binary package. It is ok if you want to do it in an extra PR, but we will merge only both together.

Updated the spec file in this PR.

2022-03-18 13:11 UTC, mcalmer approved these changes

2022-03-18 13:14 UTC, merged